In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns


In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [ ]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                              Review  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Unnamed: 0         23486 non-null  int64 
 1   Clothing ID        23486 non-null  int64 
 2   Age                23486 non-null  int64 
 3   Title              19676 non-null  object
 4   Review             22641 non-null  object
 5   Rating             23486 non-null  int64 
 6   Recommended IND    23486 non-null  int64 
 7   Positive Feedback  23486 non-null  int64 
 8   Division           23472 non-null  object
 9   Department         23472 non-null  object
 10  Category           23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df.shape

(23486, 11)

**MISSING VALUE**

In [ ]:
df.isna().sum()

Unnamed: 0              0
Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended IND         0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df[df['Review']==""]=np.NaN

In [ ]:
df['Review'].fillna("No Review", inplace=True)

In [ ]:
df.isna().sum()

Unnamed: 0              0
Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended IND         0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

**DEFINE LABEL y and featuerea x**

In [ ]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review', 'Rating',
       'Recommended IND', 'Positive Feedback', 'Division', 'Department',
       'Category'],
      dtype='object')

In [ ]:
X=df['Review']

In [ ]:
y = df['Rating']

In [ ]:
df['Rating'].value_counts()

5    13131
4     5077
3     2871
2     1565
1      842
Name: Rating, dtype: int64

In [ ]:
X.shape

(23486,)

In [ ]:
y.shape

(23486,)

In [ ]:
X

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [ ]:
y

0        4
1        5
2        3
3        5
4        5
        ..
23481    5
23482    3
23483    3
23484    3
23485    5
Name: Rating, Length: 23486, dtype: int64

# train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, stratify = y ,random_state=102529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

feature text Conversion to tokens


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3), stop_words = 'english', max_features=5000  )

In [ ]:
X_train = cv.fit_transform(X_train)

In [ ]:
cv.get_feature_names_out()

array(['0p fit', '10 10', '10 12', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test = cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 fit', '10 got', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#GET MODEL


In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit( X_train,y_train )

MultinomialNB()

# MODEL PREDICTION


In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([5, 1, 5, ..., 3, 4, 4])

#GET MODEL EVALUATION

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
confusion_matrix( y_test, y_pred )

array([[  18,   28,   29,   48,  130],
       [  60,   40,   46,  102,  222],
       [ 101,   86,  100,  185,  389],
       [ 191,  161,  166,  321,  684],
       [ 421,  401,  355,  788, 1974]])

In [ ]:
print(classification_report( y_test, y_pred ))

              precision    recall  f1-score   support

           1       0.02      0.07      0.03       253
           2       0.06      0.09      0.07       470
           3       0.14      0.12      0.13       861
           4       0.22      0.21      0.22      1523
           5       0.58      0.50      0.54      3939

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046

